### ISSUE TITLE
Deploy sample to Github pages

### ISSUE THREAD

**Issue by alorma** [WojciechOsak/Calendar#9]
Hi @WojciechOsak .

I just landed on this repo, it looks promising, as calendar is always a hard thing to build.

I just seen that you have a sample for `jsMain`, and thought that you may like the idea of building the sample for `js` and deploy it to Github pages, that way it can be tested easily for users without needing to build the code.

I have this code on my repository, that does all the work to deploy it to GH Pages:

> https://github.com/alorma/Compose-Settings/blob/main/.github/workflows/main.yml#L209-L236

```yml
  # Deployment job
  deploy:
    name: Deploy to Github pages
    if: ${{ success() }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [ build-sample ]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - name: Build sample JS - Main
        run: ./gradlew jsBrowserDistribution

      - name: Upload your page as github pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: composeApp/build/dist/js/productionExecutable/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

Maybe you will need this too:

> https://github.com/alorma/Compose-Settings/blob/main/.github/workflows/main.yml#L8C1-L12C18

```yml
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
```

Thank you!
